/// Generated by Flutter GetX Starter on 2022-09-05 15:53
import 'package:get/get.dart';
import 'package:smartmkran/app/pages/splash/view.dart';


class Routes {

  static const SPLASH = '/Splash';


  static final routes = [
    GetPage(
      name: Routes.SPLASH,
      page: () => SplashPage(),
    ),

  ];
}